[workspace]
members = [
    "canvas",
    "demo/android/rust",
    "demo/common",
    "demo/magicleap",
    "demo/native",
    "examples/canvas_minimal",
    "examples/canvas_moire",
    "examples/canvas_text",
    "geometry",
    "gl",
    "gpu",
    "renderer",
    "simd",
    "svg",
    "text",
    "ui",
    "utils/area-lut",
    "utils/gamma-lut",
    "utils/svg-to-skia"
]
