[package]
name = "pathfinder_font_renderer"
version = "0.2.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[features]
default = []
freetype-backend = ["freetype"]

[dependencies]
app_units = "0.6"
libc = "0.2"
log = "0.3"
lyon_geom = "0.10"
lyon_path = "0.10"
serde = "1.0"
serde_derive = "1.0"

[dependencies.euclid]
version = "0.17"
features = ["serde"]

[dependencies.freetype]
git = "https://github.com/servo/rust-freetype"
optional = true

[target.'cfg(not(target_os = "macos"))'.dependencies]
freetype = { git = "https://github.com/servo/rust-freetype" }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.13"
core-text = "9.2"

[target.'cfg(target_os = "windows")'.dependencies]
dwrite-sys = "0.2"
kernel32-sys = "0.2"
uuid-sys = "0.1"
winapi = "0.2"

[dev-dependencies]
env_logger = "0.5"
