[package]
name = "pathfinder_font_renderer"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[features]
default = []
freetype = ["freetype-sys"]

[dependencies]
app_units = "0.6"
euclid = "0.16"
libc = "0.2"
log = "0.3"
lyon_geom = "0.9"
lyon_path = "0.9"
serde = "1.0"
serde_derive = "1.0"

[dependencies.freetype-sys]
version = "0.6"
optional = true

[target.'cfg(not(target_os = "macos"))'.dependencies]
freetype-sys = "0.6"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.13"

[target.'cfg(target_os = "macos")'.dependencies.core-text]
git = "https://github.com/servo/core-text-rs.git"

[target.'cfg(target_os = "windows")'.dependencies]
dwrite-sys = "0.2"
kernel32-sys = "0.2"
uuid-sys = "0.1"
winapi = "0.2"

[dev-dependencies]
env_logger = "0.4"
