[package]
name = "pathfinder_path_utils"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[dependencies]
arrayvec = "0.4"
euclid = "0.16"
lyon_geom = "0.9"
lyon_path = "0.9"
serde = "1.0"
serde_derive = "1.0"
