[package]
name = "pathfinder_path_utils"
version = "0.2.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
description = "Miscellaneous BÃ©zier curve algorithms"
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.4"
lyon_path = "0.12"
serde = "1.0"
serde_derive = "1.0"
